# Generated by Django 5.1.3 on 2024-11-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingitem',
            old_name='quantity',
            new_name='number_of_people',
        ),
    ]
