# Generated by Django 5.1.3 on 2024-12-24 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='destination_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.destinations'),
        ),
    ]
