# Generated by Django 5.1.2 on 2024-11-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        
    ]
