# Generated by Django 5.1.2 on 2024-11-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_remove_packages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=9, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
