# Generated by Django 5.1.3 on 2024-11-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_rename_quantity_bookingitem_number_of_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='itinerary',
            field=models.IntegerField(choices=[(1, '1 days'), (2, '2 days'), (3, '3 days'), (4, '4 days'), (5, '5 days'), (6, '6 days'), (7, '7 days'), (8, '8 days'), (9, '9 days'), (10, '10 days')], default=3),
            preserve_default=False,
        ),
    ]
