# Generated by Django 5.1.2 on 2024-11-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
