# Generated by Django 5.1.3 on 2024-11-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_destinations_itinerary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='description',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='images',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='start_date',
        ),
        migrations.AddField(
            model_name='destinations',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
