# Generated by Django 5.1.1 on 2024-10-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='destination',
            field=models.CharField(default='Unknown Destination', max_length=255),
        ),
        migrations.AddField(
            model_name='packages',
            name='end_date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='packages',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='packages',
            name='start_date',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
