# Generated by Django 5.1.3 on 2024-11-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_remove_packages_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='activities',
            field=models.ManyToManyField(related_name='destinations', to='packages.activities'),
        ),
        migrations.AddField(
            model_name='destinations',
            name='rating',
            field=models.IntegerField(choices=[(1, '1*'), (2, '2*'), (3, '3*'), (4, '4*')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinations',
            name='review',
            field=models.CharField(default=3, max_length=500),
            preserve_default=False,
        ),
    ]
