# Generated by Django 5.1.3 on 2024-11-06 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_destinations_activities_destinations_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingitem',
            name='package_name',
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='destination_name',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='packages.destinations'),
            preserve_default=False,
        ),
    ]
