# Generated by Django 5.1.1 on 2024-10-05 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], max_length=50)),
                ('packages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.packages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('packages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.packages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.user')),
            ],
        ),
    ]
