# Generated by Django 5.1.3 on 2024-11-15 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='package',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='destinations',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='packages.destinations'),
            preserve_default=False,
        ),
    ]
