# Generated by Django 5.1.3 on 2024-11-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_remove_destinations_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='destinations',
            name='images_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='destinations',
            name='images_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.DeleteModel(
            name='DestinationImage',
        ),
    ]
