# Generated by Django 5.1.3 on 2024-11-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_alter_destinations_itinerary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1*'), (2, '2*'), (3, '3*'), (4, '4*')], null=True),
        ),
    ]
