# Generated by Django 5.1.3 on 2024-12-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_alter_destinations_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='best_season',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destinations',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destinations',
            name='map_images',
            field=models.ImageField(blank=True, null=True, upload_to='map_images/'),
        ),
        migrations.AddField(
            model_name='destinations',
            name='pradesh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1*'), (2, '2*'), (3, '3*'), (4, '4*'), (5, '5*')], null=True),
        ),
    ]
