# Generated by Django 5.1.3 on 2024-12-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='best_season',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinations',
            name='location',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinations',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='destinations',
            name='pradesh',
            field=models.CharField(default=9, max_length=100),
            preserve_default=False,
        ),
    ]
