# Generated by Django 5.1.3 on 2024-12-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_destinations_best_season_destinations_location_and_more'),
        ('packages', '0016_destinations_best_season_destinations_location_and_more'),
    ]

    operations = [
    ]
