# Generated by Django 5.1.3 on 2024-12-22 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0017_merge_20241222_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='arrival_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='nationality',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
