# Generated by Django 5.1.3 on 2024-12-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0019_bookingitem_email_bookingitem_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='map_images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
