# Generated by Django 5.1.3 on 2024-12-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0020_alter_destinations_map_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinations',
            name='map_images',
        ),
        migrations.AlterField(
            model_name='destinations',
            name='best_season',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destinations',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destinations',
            name='pradesh',
            field=models.CharField(default=7, max_length=100),
            preserve_default=False,
        ),
    ]
